from enum import Enum

class BUFF(Enum):
    AUTOCLICK = 0
    GOLDBUFF = 1
    BRICK17 = 2
    X2SCOREMULTIPLIER = 3
    X3SCOREMULTIPLIER = 4
    X4SCOREMULTIPLIER = 5
    X5SCOREMULTIPLIER = 6
    X6SCOREMULTIPLIER = 7
    X7SCOREMULTIPLIER = 8
    X8SCOREMULTIPLIER = 9
    X9SCOREMULTIPLIER = 10
    X10SCOREMULTIPLIER = 11
    INCREASEHITBOX = 12
    SHOPPROMOTION = 13
    LUCKY = 14
    TIMESLOWDOWN = 15
    PERIODICTHORTUHNDER = 16
    